#!/bin/sh

# This is a little "wrapper" shell script, which runs ./elvis with elvispath
# set to "lib".  This is handy for testing before it is installed.

ELVISPATH=data:doc:~/.elvis
export ELVISPATH
case "$1" in
  ddd|-ddd|--ddd)
	shift;
	exec ddd ./elvis "$@"
	;;
  *)
	exec ./elvis "$@"
	;;
esac
