$1
$1 - $2 version leaked
$1 - buffer disappeared, undo/redo not freed
$1 - undolnptr version leaked
$1 doesn't allow address 0
$1 doesn't exist
$1 doesn't use addresses
$1 exists
$1 is a boolean option
$1 is illegal during initialization
$1 is illegal in vi mode
$1 is locked
$1 is not a boolean option
$1 is not a file
$1 is unsafe
$1 is used internally by elvis
$1 lines deleted
$1 lines pasted
$1 lines yanked
$1 modified, not saved
$1 more lines yanked
$1 must be between $2 and $3
$1 must be between 0 and $2
$1 must be number
$1 must be one of {$2}
$1 only works on main buffer
$1 only works on window's main buffer
$1 pages
$1 readonly
$1 requires a command
$1 requires a file name
$1 requires a numeric argument
$1 requires a numeric value
$1 requires an argument
$1 requires destination
$1 rows, $2 columns
$1 substitutions on $2 lines
$1 unreadable
$1 unwritable
$1,$2 = $3 lines
$1: no such session, errno=$2
$1:($2>>50)
'$1 in other buffer
'$1 unset
+$1 $2 $3
-courier requires a font size
-geometry requires a size and/or position
<< and >> only partially implemented
For more information about user interfaces, give the command 'elvis -G?'
NUL not allowed in file name
Report bugs to $1
TERM=$1 unknown
\(\) mismatch
aborted
already in use
anchor $1 not found
args must be \$1 through \$$1
background can't be bright
bad >>
bad argument to :z
bad command name $1
bad cut buffer
bad cutbuf $1
bad delta
bad display mode $1
bad line number
bad lptype
bad mark name
bad operator
bad operator $1
bad option name $1
bad path $1
bad percentage
bad range
bad search
bad undo level
bad width
bad window
blkopen's read failed
blkread failed
blkwrite failed
broken pipe
can't $1 rectangles
can't append to filter
can't change directory
can't create pipe
can't create temp file $1
can't fork
can't load font $1
can't make temporary file
can't mix number and 'g' flag
can't retitle internal buffers
can't run $1
can't use \@ during initialization
check other buffers
color $1 $2
color $1 $2 on $3
could not allocate color $1
could not contact X server
could not find default session file
cursor not on word
cut buffer $1 empty
cut buffer $1 scrambled
cut buffer name required
destination can't be inside source
digraphs must be composed of two characters
directory name required
division by 0
error opening $1
filename required
filter name is missing
gui-specific commands not supported
header file $1 not found
help not available; couldn't load $1
help unavailable; html mode is disabled
invalid $1 $2
invalid color $1
invalid gui $1
keywordprg not set
line $1+$2: $3
line $1-$2: $3
line $1: $2
malformed file name $1
match is zero-length
missing foreground color
missing lhs
missing rhs
missing }
modified, not written
more files
must set lpout
must set normal colors first
no color support
no colors have been set
no file name
no filter
no gui available
no help available for $1
no match
no match above
no match below
no memory
no more errors
no more files
no previous RE
no previous char search
no previous command
no previous cut buffer
no previous file
no previous search
no previous tag
no previous text to substitute for ~
no such buffer
no such session
no such window
no value to substitute for $1
non-local URLs aren't supported yet
not main buffer
not that many lines in buffer
not while in open mode
nothing to join with this line
only $1 lines
only works on window's default buffer
oops
prgwrite(..., $1) returning $2
reading $1
set \$SESSIONPATH to a writable directory
skipping old session file $1
substitution failed
tag $1 not found
tag stack empty
termcap database unreadable
termcap needs $1
this gui only supports ex mode
too few \\\(\\\)s to use \\$1
too many arguments for $1
too many files
unknown function $1
unsafe filter
unsupported flag '$1'
using open mode
would span buffers
wrapped
writing $1
