$1
$1 - $2 version leaked
$1 - buffer disappeared, undo/redo not freed
$1 - undolnptr version leaked
$1 doesn't allow address 0
$1 doesn't exist
$1 doesn't use addresses
$1 exists
$1 is a boolean option
$1 is illegal during initialization
$1 is illegal in vi mode
$1 is locked
$1 is not a boolean option
$1 is not a file
$1 is unsafe
$1 is used internally by elvis
$1 lines deleted
$1 lines joined
$1 lines pasted
$1 lines yanked
$1 modified, not saved
$1 more lines yanked
$1 must be between $2 and $3
$1 must be between 0 and $2
$1 must be number
$1 must be one of {$2}
$1 not a remote url
$1 only works on main buffer
$1 only works on window's main buffer
$1 pages
$1 readonly
$1 requires a command
$1 requires a file name
$1 requires a numeric argument
$1 requires a numeric value
$1 requires an argument
$1 requires destination
$1 requires two arguments
$1 rows, $2 columns
$1 substitutions on $2 lines
$1 unreadable
$1 unwritable
$1,$2 = $3 lines
$1,$2: file still open from $3,$4
$1: no such session, errno=$2
$1:($2>>50)
'$1 in other buffer
'$1 unset
(buflines) lines
+$1 $2 $3
, nMin=0, nMax=$1, nPage=$2, nPos=$3
-courier requires a font size
-geometry requires a size and/or position
:$1
<< and >> only partially implemented
Flags: -V          Verbose -- give more status information
For more information about user interfaces, give the command 'elvis -G?'
NUL not allowed in file name
Ported to (os) by $1
Report bugs to $1
TERM=$1 unknown
Usage: elvis  [files]...
User interfaces: $1
\(\) mismatch
aborted
alias names must be alphanumeric
already in use
anchor $1 not found
args must be \$1 through \$$1
background can't be bright
bad >>
bad argument to :z
bad command name $1
bad cut buffer
bad cutbuf $1
bad delta
bad display mode $1
bad elvis.bdf
bad line number
bad lptype
bad mark name
bad operator
bad operator $1
bad option name $1
bad path $1
bad percentage
bad range
bad search
bad undo level
bad window
blkopen's read failed
blkread failed
blkwrite failed
blkwrite failed -- not enough EMS/XMS memory
broken pipe
buffer $1 is locked
can only READ from http $1
can only READ ftp directories
can't $1 rectangles
can't append to filter
can't change directory
can't create pipe
can't create temp file $1
can't dup file handle
can't fork
can't load font $1
can't make temporary file
can't mix instance number .$1 and g flag
can't paste a buffer into itself
can't redefine $1 because it is in use
can't restore local $1
can't run $1
can't spawn
can't unalias $1 because it is in use
can't use \\@ during initialization
can't yank a buffer into itself
check other buffers
color $1 $2
color $1 $2 on $3
connecting to $1
could not allocate color $1
could not connect
could not contact X server
could not create socket
could not find default session file
could not send request to server
cursor not on word
cut buffer $1 empty
cut buffer name required
destination can't be inside source
digraphs must be composed of two characters
directory name required
division by 0
elvis $1
elvis requires winsock 1.1
error reading from socket
filename required
filter name is missing
ftp failed: $1
ftp: $1
ftp: $1 $2
ftp: passive channel = $1:$2
gui-specific commands not supported
header file $1 not found
help not available; couldn't load $1
help unavailable; html mode is disabled
htmltagload\(tagname=$1, from=$2\)
invalid $1 $2
invalid color $1
invalid gui $1
keywordprg not set
line $1+$2: $3
line $1-$2: $3
line $1: $2
looking up site $1
malformed !() in alias $1
malformed file name $1
match is zero-length
missing :while
missing foreground color
missing lhs
missing rhs
modified, not written
more files
must set lpout
must set normal colors first
network not ready
no EMS/XMS -- can't use \
no alias named $1
no buffer named $1
no color support
no colors have been set
no file name
no filter
no gui available
no help available for $1
no match
no match above
no match below
no memory
no more errors
no more files
no more lines
no previous RE
no previous char search
no previous cut buffer
no previous regular expression
no previous search
no previous tag
no previous text to substitute for ~
no such session
no such window
no tool
no value to substitute for $1
not that many lines in buffer
not while in open mode
nothing to join with this line
only $1 lines
only works on window's default buffer
oops
prgwrite(..., $1) returning $2
protocol=$1, site_port=$2, resource=$3
reading $1
reading directory
receiving...
receiving... $1 bytes
receiving... $1 of $2 bytes
regcomp error: calced=$1, actual=$2
requesting $1
result too long
sending... $1 bytes
sending... $1 of $2 bytes
session file busy
session=(session)
set SESSIONPATH to a writable directory
skipping $1 old session file($1!=1?\
substitution failed
tag address out of date
tag not found
tag stack empty
termcap database unreadable
termcap needs $1
the $1 alias doesn't use a ! suffix
the $1 alias doesn't use addresses
the $1 alias doesn't use arguments
the :$1 command is disabled
the c flag is only available from a window
the c flag only works on the window's main edit buffer
this gui only supports ex mode
too few \\\(\\\)s to use \\$1
too many arguments for $1
too many files
transmission failed
unknown function $1
unknown site $1
unsafe filter
unsafe to change $1
unsupported flag '$1'
unsupported protocol
unsupported protocol $1
user interfaces:
user=$1, password=$2, account=$3
using open mode
warning: almost out of memory
won't overwrite ftp file without '!'
would span buffers
wrapped
writing $1
your winsock supports $1.$2 - $3.$4
