#!/bin/sh

set -e

case "$1" in
    configure)
        update-alternatives --quiet \
          --install /usr/bin/ctags ctags /usr/bin/elvtags 40 \
          --slave /usr/share/man/man1/ctags.1.gz ctags.1.gz \
                  /usr/share/man/man1/elvtags.1.gz
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
